package com.example.domain.model

import androidx.compose.ui.graphics.Color

enum class ThemePreset(
    val displayName: String,
    val description: String,
    val primaryLight: Color,
    val primaryDark: Color,
    val secondaryLight: Color,
    val secondaryDark: Color,
    val surfaceLight: Color,
    val surfaceDark: Color,
    val bgLight: Color,
    val bgDark: Color,
    val tertiaryLight: Color,
    val tertiaryDark: Color,
    val errorLight: Color,
    val errorDark: Color
) {
    EMERALD_FOREST(
        displayName = "Emerald Forest",
        description = "Classic focus palette with calming greens and mint accents",
        primaryLight = Color(0xFF059669),
        primaryDark = Color(0xFF10B981),
        secondaryLight = Color(0xFF0284C7),
        secondaryDark = Color(0xFF06B6D4),
        surfaceLight = Color(0xFFFFFFFF),
        surfaceDark = Color(0xFF1E293B),
        bgLight = Color(0xFFF8FAFC),
        bgDark = Color(0xFF0F172A),
        tertiaryLight = Color(0xFF0D9488),
        tertiaryDark = Color(0xFF2DD4BF),
        errorLight = Color(0xFFDC2626),
        errorDark = Color(0xFFF87171)
    ),
    DEEP_SLATE(
        displayName = "Deep Slate & Cyan",
        description = "Tech-inspired cyan accents over deep graphite tones",
        primaryLight = Color(0xFF0284C7),
        primaryDark = Color(0xFF38BDF8),
        secondaryLight = Color(0xFF0F766E),
        secondaryDark = Color(0xFF2DD4BF),
        surfaceLight = Color(0xFFFFFFFF),
        surfaceDark = Color(0xFF182234),
        bgLight = Color(0xFFF1F5F9),
        bgDark = Color(0xFF0B1120),
        tertiaryLight = Color(0xFF8B5CF6),
        tertiaryDark = Color(0xFFA78BFA),
        errorLight = Color(0xFFDC2626),
        errorDark = Color(0xFFF87171)
    ),
    SUNSET_AMBER(
        displayName = "Sunset Amber",
        description = "Energizing warm honey, amber, and terracotta vibes",
        primaryLight = Color(0xFFD97706),
        primaryDark = Color(0xFFF59E0B),
        secondaryLight = Color(0xFFEA580C),
        secondaryDark = Color(0xFFFB923C),
        surfaceLight = Color(0xFFFFFFFF),
        surfaceDark = Color(0xFF271C19),
        bgLight = Color(0xFFFFFBEB),
        bgDark = Color(0xFF1C130E),
        tertiaryLight = Color(0xFF8B5CF6),
        tertiaryDark = Color(0xFFA78BFA),
        errorLight = Color(0xFFDC2626),
        errorDark = Color(0xFFF87171)
    ),
    MIDNIGHT_OBSIDIAN(
        displayName = "Midnight Obsidian",
        description = "Pitch OLED black with high-contrast electric jade",
        primaryLight = Color(0xFF047857),
        primaryDark = Color(0xFF34D399),
        secondaryLight = Color(0xFF4338CA),
        secondaryDark = Color(0xFF818CF8),
        surfaceLight = Color(0xFFFFFFFF),
        surfaceDark = Color(0xFF111111),
        bgLight = Color(0xFFFAFAFA),
        bgDark = Color(0xFF000000),
        tertiaryLight = Color(0xFF6366F1),
        tertiaryDark = Color(0xFF818CF8),
        errorLight = Color(0xFFE11D48),
        errorDark = Color(0xFFFB7185)
    ),
    CYBER_NEON(
        displayName = "Cyber Neon",
        description = "Synthwave electric violet and vivid magenta glows",
        primaryLight = Color(0xFF7C3AED),
        primaryDark = Color(0xFFA78BFA),
        secondaryLight = Color(0xFFDB2777),
        secondaryDark = Color(0xFFF472B6),
        surfaceLight = Color(0xFFFFFFFF),
        surfaceDark = Color(0xFF1E1735),
        bgLight = Color(0xFFFAF5FF),
        bgDark = Color(0xFF0F0B1E),
        tertiaryLight = Color(0xFF8B5CF6),
        tertiaryDark = Color(0xFFA78BFA),
        errorLight = Color(0xFFDC2626),
        errorDark = Color(0xFFF87171)
    ),
    NORDIC_FROST(
        displayName = "Nordic Frost",
        description = "Clean arctic ice blue, glacier teal, and serene slate",
        primaryLight = Color(0xFF0369A1),
        primaryDark = Color(0xFF67E8F9),
        secondaryLight = Color(0xFF334155),
        secondaryDark = Color(0xFF94A3B8),
        surfaceLight = Color(0xFFFFFFFF),
        surfaceDark = Color(0xFF1A2433),
        bgLight = Color(0xFFF0F9FF),
        bgDark = Color(0xFF0C131F),
        tertiaryLight = Color(0xFF8B5CF6),
        tertiaryDark = Color(0xFFA78BFA),
        errorLight = Color(0xFFDC2626),
        errorDark = Color(0xFFF87171)
    ),
    ROSE_QUARTZ(
        displayName = "Rose Quartz & Velvet",
        description = "Gentle blush rose, velvet plum, and soft crimson accents",
        primaryLight = Color(0xFFBE185D),
        primaryDark = Color(0xFFF472B6),
        secondaryLight = Color(0xFF9333EA),
        secondaryDark = Color(0xFFC084FC),
        surfaceLight = Color(0xFFFFFFFF),
        surfaceDark = Color(0xFF281822),
        bgLight = Color(0xFFFDF2F8),
        bgDark = Color(0xFF1A0E16),
        tertiaryLight = Color(0xFFE11D48),
        tertiaryDark = Color(0xFFFB7185),
        errorLight = Color(0xFFDC2626),
        errorDark = Color(0xFFF87171)
    ),
    ESPRESSO_MOCHA(
        displayName = "Espresso & Mocha",
        description = "Warm roasted coffee, rich bronze, and cozy oat undertones",
        primaryLight = Color(0xFF854D0E),
        primaryDark = Color(0xFFFBBF24),
        secondaryLight = Color(0xFF78350F),
        secondaryDark = Color(0xFFD97706),
        surfaceLight = Color(0xFFFFFFFF),
        surfaceDark = Color(0xFF251D1A),
        bgLight = Color(0xFFFEFCE8),
        bgDark = Color(0xFF171210),
        tertiaryLight = Color(0xFFD97706),
        tertiaryDark = Color(0xFFFBBF24),
        errorLight = Color(0xFFDC2626),
        errorDark = Color(0xFFF87171)
    ),
    LAVENDER_DREAM(
        displayName = "Lavender Dream",
        description = "Mindful soft purple, calming lilac, and gentle indigo",
        primaryLight = Color(0xFF6D28D9),
        primaryDark = Color(0xFFC4B5FD),
        secondaryLight = Color(0xFF4F46E5),
        secondaryDark = Color(0xFF818CF8),
        surfaceLight = Color(0xFFFFFFFF),
        surfaceDark = Color(0xFF201B2E),
        bgLight = Color(0xFFF5F3FF),
        bgDark = Color(0xFF13101D),
        tertiaryLight = Color(0xFFD946EF),
        tertiaryDark = Color(0xFFE879F9),
        errorLight = Color(0xFFDC2626),
        errorDark = Color(0xFFF87171)
    ),
    TOKYO_CYBERPUNK(
        displayName = "Tokyo Cyberpunk",
        description = "High-voltage neon yellow, electric cyan, and deep ink",
        primaryLight = Color(0xFFCA8A04),
        primaryDark = Color(0xFFFACC15),
        secondaryLight = Color(0xFF0891B2),
        secondaryDark = Color(0xFF22D3EE),
        surfaceLight = Color(0xFFFFFFFF),
        surfaceDark = Color(0xFF1E222D),
        bgLight = Color(0xFFFEFCE8),
        bgDark = Color(0xFF0E131F),
        tertiaryLight = Color(0xFFD946EF),
        tertiaryDark = Color(0xFFE879F9),
        errorLight = Color(0xFFEF4444),
        errorDark = Color(0xFFF87171)
    ),
    OCEAN_ABYSS(
        displayName = "Ocean Abyss",
        description = "Deep marine sapphire, aquamarine, and coastal seafoam",
        primaryLight = Color(0xFF0E7490),
        primaryDark = Color(0xFF22D3EE),
        secondaryLight = Color(0xFF1D4ED8),
        secondaryDark = Color(0xFF60A5FA),
        surfaceLight = Color(0xFFFFFFFF),
        surfaceDark = Color(0xFF142433),
        bgLight = Color(0xFFECFEFF),
        bgDark = Color(0xFF091624),
        tertiaryLight = Color(0xFF0284C7),
        tertiaryDark = Color(0xFF38BDF8),
        errorLight = Color(0xFFDC2626),
        errorDark = Color(0xFFF87171)
    ),
    MONOCHROME_MINIMALIST(
        displayName = "Monochrome Minimalist",
        description = "Zero-distraction brutalist stark black, silver, and white",
        primaryLight = Color(0xFF18181B),
        primaryDark = Color(0xFFF4F4F5),
        secondaryLight = Color(0xFF52525B),
        secondaryDark = Color(0xFFA1A1AA),
        surfaceLight = Color(0xFFFFFFFF),
        surfaceDark = Color(0xFF1E1E22),
        bgLight = Color(0xFFF4F4F5),
        bgDark = Color(0xFF121214),
        tertiaryLight = Color(0xFF52525B),
        tertiaryDark = Color(0xFFA1A1AA),
        errorLight = Color(0xFF3F3F46),
        errorDark = Color(0xFFD4D4D8)
    ),
    MATCHA_OAT(
        displayName = "Matcha & Oat",
        description = "A soothing earthy pastel blend of matcha green and warm oat",
        primaryLight = Color(0xFF8BA888),
        primaryDark = Color(0xFFA6C4A2),
        secondaryLight = Color(0xFFC7B198),
        secondaryDark = Color(0xFFDFCCB6),
        surfaceLight = Color(0xFFFDFBF7),
        surfaceDark = Color(0xFF2C302B),
        bgLight = Color(0xFFF4EFE6),
        bgDark = Color(0xFF1D201C),
        tertiaryLight = Color(0xFF65A30D),
        tertiaryDark = Color(0xFFA3E635),
        errorLight = Color(0xFFDC2626),
        errorDark = Color(0xFFF87171)
    ),
    NEON_SAKURA(
        displayName = "Neon Sakura",
        description = "Vibrant hot pink and crisp white with an anime aesthetic",
        primaryLight = Color(0xFFFF006A),
        primaryDark = Color(0xFFFF4D94),
        secondaryLight = Color(0xFF8B5CF6),
        secondaryDark = Color(0xFFA78BFA),
        surfaceLight = Color(0xFFFFFFFF),
        surfaceDark = Color(0xFF1F1118),
        bgLight = Color(0xFFFFF5F8),
        bgDark = Color(0xFF0F050A),
        tertiaryLight = Color(0xFFF43F5E),
        tertiaryDark = Color(0xFFFB7185),
        errorLight = Color(0xFFDC2626),
        errorDark = Color(0xFFF87171)
    ),
    DYNAMIC_MATERIAL(
        displayName = "Dynamic (Material You)",
        description = "Extracts colors from your wallpaper (Android 12+)",
        primaryLight = Color(0xFF10B981),
        primaryDark = Color(0xFF10B981),
        secondaryLight = Color(0xFF06B6D4),
        secondaryDark = Color(0xFF06B6D4),
        surfaceLight = Color(0xFFFFFFFF),
        surfaceDark = Color(0xFF121212),
        bgLight = Color(0xFFF8FAFC),
        bgDark = Color(0xFF000000),
        tertiaryLight = Color(0xFF8B5CF6),
        tertiaryDark = Color(0xFF8B5CF6),
        errorLight = Color(0xFFEF4444),
        errorDark = Color(0xFFEF4444)
    ),
    POWDER_BLUE_SLATE(
        displayName = "Powder Blue & Slate",
        description = "Crisp, airy pastel blue contrasting with grounded slate grey",
        primaryLight = Color(0xFF78A2CC),
        primaryDark = Color(0xFF98C1EB),
        secondaryLight = Color(0xFF7E8D9C),
        secondaryDark = Color(0xFFA4B4C4),
        surfaceLight = Color(0xFFFFFFFF),
        surfaceDark = Color(0xFF242A30),
        bgLight = Color(0xFFF0F4F8),
        bgDark = Color(0xFF161A1D),
        tertiaryLight = Color(0xFF6366F1),
        tertiaryDark = Color(0xFF818CF8),
        errorLight = Color(0xFFDC2626),
        errorDark = Color(0xFFF87171)
    ),
    LAVENDER_HAZE(
        displayName = "Lavender Haze",
        description = "A dreamy, muted pastel lavender and misty silver palette",
        primaryLight = Color(0xFF9A8C98),
        primaryDark = Color(0xFFC9B6E4),
        secondaryLight = Color(0xFFC9ADA7),
        secondaryDark = Color(0xFFE2CFCB),
        surfaceLight = Color(0xFFF9F8F9),
        surfaceDark = Color(0xFF2B2830),
        bgLight = Color(0xFFF2E9E4),
        bgDark = Color(0xFF1C1920),
        tertiaryLight = Color(0xFFD946EF),
        tertiaryDark = Color(0xFFE879F9),
        errorLight = Color(0xFFDC2626),
        errorDark = Color(0xFFF87171)
    ),
    TERRACOTTA_SAGE(
        displayName = "Muted Terracotta & Sage",
        description = "Earthy baked clay hues accented with organic sage green",
        primaryLight = Color(0xFFCB857C),
        primaryDark = Color(0xFFE09A91),
        secondaryLight = Color(0xFF8C9A86),
        secondaryDark = Color(0xFFA5B49F),
        surfaceLight = Color(0xFFFEFDFB),
        surfaceDark = Color(0xFF302B29),
        bgLight = Color(0xFFF9F3F0),
        bgDark = Color(0xFF221C1A),
        tertiaryLight = Color(0xFFD97706),
        tertiaryDark = Color(0xFFFBBF24),
        errorLight = Color(0xFFDC2626),
        errorDark = Color(0xFFF87171)
    ),
    DESERT_SAND(
        displayName = "Desert Sand",
        description = "Warm, minimalist sandy beige and soft dune tones",
        primaryLight = Color(0xFFD4A373),
        primaryDark = Color(0xFFEBC193),
        secondaryLight = Color(0xFFCCD5AE),
        secondaryDark = Color(0xFFE9F5C7),
        surfaceLight = Color(0xFFFFFFFF),
        surfaceDark = Color(0xFF332D28),
        bgLight = Color(0xFFFAEDCD),
        bgDark = Color(0xFF221C17),
        tertiaryLight = Color(0xFFCA8A04),
        tertiaryDark = Color(0xFFFACC15),
        errorLight = Color(0xFFDC2626),
        errorDark = Color(0xFFF87171)
    ),
    MINT_MILK(
        displayName = "Mint Milk",
        description = "Refreshing pastel mint green over a smooth milky canvas",
        primaryLight = Color(0xFF73C0B1),
        primaryDark = Color(0xFF90E0D1),
        secondaryLight = Color(0xFF88A0A8),
        secondaryDark = Color(0xFFABC5CD),
        surfaceLight = Color(0xFFFFFFFF),
        surfaceDark = Color(0xFF253330),
        bgLight = Color(0xFFF0FDF8),
        bgDark = Color(0xFF15201E),
        tertiaryLight = Color(0xFF10B981),
        tertiaryDark = Color(0xFF34D399),
        errorLight = Color(0xFFDC2626),
        errorDark = Color(0xFFF87171)
    ),
    EVA_RED(
        displayName = "EVA Red",
        description = "Striking scarlet and bold hazard orange on dark charcoal",
        primaryLight = Color(0xFFDC2626),
        primaryDark = Color(0xFFEF4444),
        secondaryLight = Color(0xFFF97316),
        secondaryDark = Color(0xFFFB923C),
        surfaceLight = Color(0xFFFFFFFF),
        surfaceDark = Color(0xFF291E1E),
        bgLight = Color(0xFFFEF2F2),
        bgDark = Color(0xFF171010),
        tertiaryLight = Color(0xFFEAB308),
        tertiaryDark = Color(0xFFFDE047),
        errorLight = Color(0xFFDC2626),
        errorDark = Color(0xFFF87171)
    ),
    EVA_PURPLE(
        displayName = "EVA Purple",
        description = "Intense mecha violet paired with toxic neon green",
        primaryLight = Color(0xFF7E22CE),
        primaryDark = Color(0xFFA855F7),
        secondaryLight = Color(0xFF16A34A),
        secondaryDark = Color(0xFF4ADE80),
        surfaceLight = Color(0xFFFFFFFF),
        surfaceDark = Color(0xFF201B2E),
        bgLight = Color(0xFFF5F3FF),
        bgDark = Color(0xFF130E1F),
        tertiaryLight = Color(0xFFF97316),
        tertiaryDark = Color(0xFFFB923C),
        errorLight = Color(0xFFDC2626),
        errorDark = Color(0xFFF87171)
    ),
    ZEN_ZONE_ORANGE(
        displayName = "Zen Zone Orange",
        description = "High-energy vibrant orange, crisp yellow, and deep static gray",
        primaryLight = Color(0xFFEA580C),
        primaryDark = Color(0xFFFB923C),
        secondaryLight = Color(0xFFEAB308),
        secondaryDark = Color(0xFFFDE047),
        surfaceLight = Color(0xFFFFFFFF),
        surfaceDark = Color(0xFF262626),
        bgLight = Color(0xFFFFF7ED),
        bgDark = Color(0xFF171717),
        tertiaryLight = Color(0xFFF59E0B),
        tertiaryDark = Color(0xFFFCD34D),
        errorLight = Color(0xFFDC2626),
        errorDark = Color(0xFFF87171)
    ),
    CRIMSON_LANCER(
        displayName = "Crimson Lancer",
        description = "Deep burgundy red, mystic violet, and shadowy battlefields",
        primaryLight = Color(0xFF9F1239),
        primaryDark = Color(0xFFF43F5E),
        secondaryLight = Color(0xFF5B21B6),
        secondaryDark = Color(0xFF8B5CF6),
        surfaceLight = Color(0xFFFFFFFF),
        surfaceDark = Color(0xFF251A1D),
        bgLight = Color(0xFFFFF1F2),
        bgDark = Color(0xFF170F12),
        tertiaryLight = Color(0xFF9333EA),
        tertiaryDark = Color(0xFFC084FC),
        errorLight = Color(0xFFDC2626),
        errorDark = Color(0xFFF87171)
    )
}
